import type { Brand } from "../lib/types";

export function makeBrand(over: Partial<Brand> = {}): Brand {
  return {
    id: "00000000-0000-0000-0000-000000000001",
    brand_name: "테스트브랜드",
    brand_name_en: "",
    biz_no: null,
    email: "test@example.com",
    phone: null,
    contact_name: "홍길동",
    category: "뷰티",
    brand_url: "",
    state: "lead_new",
    contract_type: null,
    source: "glovek_consult",
    plan: null,
    pay_status: "none",
    countries: [],
    grade: null,
    rec_track: null,
    churn_risk: "low",
    certified_countries: [],
    brief_md: null,
    owner_intake: null,
    owner_sales: null,
    owner_onboard: null,
    owner_ads: null,
    next_action: "",
    due_date: null,
    last_contact_at: null,
    stage_entered_at: "2026-07-20T00:00:00Z",
    glovek_user_id: null,
    glovek_onb_id: null,
    apply_customer_id: null,
    apply_app_id: null,
    tp_registration_id: null,
    referral_code: null,
    memo: "",
    is_test: false,
    version: 1,
    owner_backup: null,
    notion_page_url: null,
    created_at: "2026-07-20T00:00:00Z",
    updated_at: "2026-07-20T00:00:00Z",
    ...over,
  };
}
